### ISSUE TITLE
Connection to back instance - Session key is not present

### ISSUE THREAD

**Issue by shiva4983** [healenium/healenium-web#69]
Hi @Aliaksei-Ashukha 

I try to monitor the backend instance and when the self healing step is executing, I am seeing the below error in the backend log.

2020-11-20 23:43:25.549 WARN 1 - [7878-exec-6] c.e.h.c.HealingController : Session key is not present. Current issue would not be presented in any reports, but still available in replacement!

2020-11-20 23:43:25.849 INFO 1 - [7878-exec-6] Manager$PushGatewayTaskScheduler : Shutting down ExecutorService

2020-11-20 23:43:35.845 ERROR 1 - [Scheduler-1] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out\n at java.net.PlainSocketImpl.socketConnect(Native Method)\n at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n at java.net.Socket.connect(Socket.java:607)\n at sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)\n at sun.net.www.http.HttpClient.New(HttpClient.java:339)\n at sun.net.www.http.HttpClient.New(HttpClient.java:357)\n at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)\n at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)\n at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:305)\n at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)\n at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\n at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n at java.lang.Thread.run(Thread.java:748)\n

2020-11-20 23:43:35.864 ERROR 1 - [7878-exec-6] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out\n at java.net.PlainSocketImpl.socketConnect(Native Method)\n at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n at java.net.Socket.connect(Socket.java:607)\n at sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)\n at sun.net.www.http.HttpClient.New(HttpClient.java:339)\n at sun.net.www.http.HttpClient.New(HttpClient.java:357)\n at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)\n at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)\n at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:305)\n at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.shutdown(PrometheusPushGatewayManager.java:146)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.shutdown(PrometheusPushGatewayManager.java:136)\n at com.epam.healenium.service.impl.HealingServiceImpl.saveHealing(HealingServiceImpl.java:106)\n at com.epam.healenium.service.impl.HealingServiceImpl$$FastClassBySpringCGLIB$$7275c128.invoke(<generated>)\n at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)\n at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)\n at com.epam.healenium.service.impl.HealingServiceImpl$$EnhancerBySpringCGLIB$$3a0d7c36.saveHealing(<generated>)\n at com.epam.healenium.controller.HealingController.save(HealingController.java:72)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\n at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)\n at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)\n at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\n at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\n at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\n at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)\n at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\n at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)\n at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\n at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)\n at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)\n at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)\n at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n at java.lang.Thread.run(Thread.java:748)\n

**Comment by Aliaksei-Ashukha** [comment]
Hi @shiva4983,

Issue was fixed in 3.0.7 version of healenium/hlm-backend service.
Please check

**Comment by Aliaksei-Ashukha** [comment]
Discussion was moved to https://github.com/healenium/healenium-web/issues/63

**Comment by shiva4983** [comment]
Hi @Aliaksei-Ashukha, thanks for clarifying however I am getting the below error while using 3.0.7 or the latest

healenium_1 | 2020-11-23 23:33:50.956 WARN 1 - [ main] rvletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n

healenium_1 | 2020-11-23 23:33:50.957 INFO 1 - [ main] c.z.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated...

healenium_1 | 2020-11-23 23:33:50.983 INFO 1 - [ main] c.z.hikari.HikariDataSource : HikariPool-1 - Shutdown completed.

healenium_1 | 2020-11-23 23:33:50.991 INFO 1 - [ main] o.a.c.core.StandardService : Stopping service [Tomcat]

healenium_1 | 2020-11-23 23:33:51.033 INFO 1 - [ main] nEvaluationReportLoggingListener : \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

healenium_1 | 2020-11-23 23:33:51.056 ERROR 1 - [ main] o.s.boot.SpringApplication : Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n \n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)\n at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)\n at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)\n at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)\n at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)\n at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)\n at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)\n at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n at com.epam.healenium.Application.main(Application.java:9)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n Caused by: liquibase.exception.ValidationFailedException: Validation Failed:\n 1 change sets check sum\n changelog/004_healingResult.xml::9::nkobzev was: 8:b916839b9918e0ec04ce87be4dfee7d2 but is now: 8:899edd768cc023ad1824af1eb759b375\n \n at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:291)\n at liquibase.Liquibase.update(Liquibase.java:198)\n at liquibase.Liquibase.update(Liquibase.java:179)\n at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366)\n at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)\n ... 26 common frames omitted\n

healeniumbackend_healenium_1 exited with code 1

**Comment by shiva4983** [comment]
After pulling postgresql fresh image resolved the issue.

**Comment by shiva4983** [comment]
Hi @Aliaksei-Ashukha 

this issue persist.. I am using the latest version.

2020-11-24 00:13:06.322 WARN 1 - [7878-exec-6] c.e.h.c.HealingController : Session key is not present. Current issue would not be presented in any reports, but still available in replacement!

2020-11-24 00:13:07.834 INFO 1 - [7878-exec-6] Manager$PushGatewayTaskScheduler : Shutting down ExecutorService



2020-11-24 00:13:18.430 ERROR 1 - [Scheduler-1] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out\n at java.net.PlainSocketImpl.socketConnect(Native Method)\n at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n at java.net.Socket.connect(Socket.java:607)\n at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)\n at sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)\n at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)\n at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)\n at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)\n at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)\n at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:305)\n at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)\n at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\n at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n at java.lang.Thread.run(Thread.java:748)\n

2020-11-24 00:13:18.432 ERROR 1 - [7878-exec-6] e.p.PrometheusPushGatewayManager : Unable to push metrics to Prometheus Pushgateway java.net.SocketTimeoutException: connect timed out\n at java.net.PlainSocketImpl.socketConnect(Native Method)\n at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n at java.net.Socket.connect(Socket.java:607)\n at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)\n at sun.net.NetworkClient.doConnect(NetworkClient.java:175)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)\n at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)\n at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)\n at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)\n at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)\n at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)\n at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)\n at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)\n at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:305)\n at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.push(PrometheusPushGatewayManager.java:108)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.shutdown(PrometheusPushGatewayManager.java:146)\n at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusPushGatewayManager.shutdown(PrometheusPushGatewayManager.java:136)\n at com.epam.healenium.service.impl.PrometheusServiceImpl.pushAndClear(PrometheusServiceImpl.java:41)\n at com.epam.healenium.service.impl.PrometheusServiceImpl$$FastClassBySpringCGLIB$$27ceebfe.invoke(<generated>)\n at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)\n at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)\n at com.epam.healenium.service.impl.PrometheusServiceImpl$$EnhancerBySpringCGLIB$$602b1f2c.pushAndClear(<generated>)\n at com.epam.healenium.service.impl.HealingServiceImpl.saveHealing(HealingServiceImpl.java:101)\n at com.epam.healenium.service.impl.HealingServiceImpl$$FastClassBySpringCGLIB$$7275c128.invoke(<generated>)\n at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)\n at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)\n at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\n at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)\n at com.epam.healenium.service.impl.HealingServiceImpl$$EnhancerBySpringCGLIB$$b81128ea.saveHealing(<generated>)\n at com.epam.healenium.controller.HealingController.save(HealingController.java:73)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\n at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)\n at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)\n at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\n at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\n at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\n at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)\n at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\n at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)\n at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\n at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)\n at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)\n at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)\n at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n at java.lang.Thread.run(Thread.java:748)\n
